spring.application.name=bancoxyz

spring.datasource.url=jdbc:h2:mem:bancoxyz;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true

bancoxyz.archivo-cuentas-anuales:classpath:data/cuentas_anuales.csv
bancoxyz.archivo-intereses:classpath:data/intereses.csv
bancoxyz.archivo-transacciones:classpath:data/transacciones.csv

logging.level.org.springframework.batch=INFO
logging.level.cl.duoc.rutaexpress=DEBUG